travis:
  secure:
    BINSTAR_TOKEN: Fh0U2vuoImLihyOtdXztqFIL7cabQ08BDLeXBgC4ya9mCgcCbuVOuBTc9ArV0ZsMIFrpIOC9nJUiAGPmkLzavbrxTnUVgjUPgMZ3lB1gOr7OAYedHc21GMHH5p3IpaTOuem/fskjiYKBu4OJ2tCak+Dp1fATnK/FK1VNcoE0+EuOLn8XM2WWvHLqELbecBqJtPlF4Y+zFvbkwBQccaNfyIXvwqM4LfQavDtZuLnYxESGPr2doMQ4jvxTtiQjkhJpppeJKumP8z1iBJxBrulxLCfzw0pXRutceWiLfglXryHtQrZ0ic+nUa7pbJ++65lyD21FiaILlCTc3r1P0XslC25BQaNPzPQKmwMubkAN3SXsQCwXnYrMoWzxTw7UAEn+5pDta+Wjuz228Bupp70D0wKKr1mqErW4asJyYVUA5a4tfkQvYlLqJZHIYN933FwcVc/H1CkZObeJR75qQKLVIomL7MJSJRDu8b2E23Sd6EAE3KWOnT6hF+uqLvtyMWMyR4fMDhE+KT+3D3QY8RcoH1xvGk8QB2nX8fxD3yhcgJtO6D/oNHq05tz+iuFdD2HgruIZLyeq57fkQBXLOD7TiRHnQtLneQ9xXIlR1EG5F1gtq29gOr7bJTTzj/84pPSGziKPEHXlaEzkd1FyLv/JUGxXhtIiIVpFGW5OmcefRWA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
